### ISSUE TITLE
Redirect LOOP with specific URLs

### ISSUE THREAD

**Issue by patricknn** [Mashape/unirest-nodejs#85]
This is simple

I'm creating a crawler using the unirest module and for some urls that have strange characters like this one, I get a redirect loop

Here it is the example:

http://www.casasbahia.com.br/Moveis/EscritorioHomeOffice/EstacoesdeTrabalho/Mesa-para-Computador-2ultivisao-–-Branco-25231.html

If you open in your browser you get a 200 response after a single 301 redirect but if you try to get using the unirest module I get a infinite 301

This is not a cookie problem, this is a character encoding issue.

It looks like that the url to be redirected is not being decoded or encoded properly

"this issue also happen with the request module, the http module does not have this issue but I need proxies and the http module proxies aren't a good option"

**Comment by patricknn** [comment]
I found a solution:

The issue is really the strange character called EN DASH

I'm using the http module and making the redirect by my self to control the URL to redirect.

So, first I decode the URL in utf-8 using the iconv module
then I encode the URL 
then I replace the code of the mandatory characters like / : ? & =

and then I make the request and everything runs perfectly

Here it is some code
var sNewUrl = iconv.decode(res.headers['location'], 'utf-8');
sNewUrl = encodeURIComponent(sNewUrl);
sNewUrl = sNewUrl.replace(/\%2F/g,"/");
sNewUrl = sNewUrl.replace(/\%3A/g,":");
sNewUrl = sNewUrl.replace(/\%3F/g,"?");
sNewUrl = sNewUrl.replace(/\%3D/g,"=");
sNewUrl = sNewUrl.replace(/\%26/g,"&");

Probably there is a better way to do it.

**Comment by ahmadnassri** [comment]
hey @patricknn In general URIs as defined by [RFC 3986](https://tools.ietf.org/html/rfc3986) ([Section 2: Characters](http://tools.ietf.org/html/rfc3986#section-2)) may contain any of the following characters: `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=`.

Any other character needs to be encoded with the percent-encoding.

so this wouldn't be a unirest bug, and the redirect is most likely coming from the casasbahia server, which does not like EN DASH being encoded into `%E2%80%93` it sends a redirect to the "wrong" version `–` where unirest correctly encodes it and sends it again, therefore ends up in a loop....

if you're the site author, then you should probably correct this, doubtful any of the major http libraries will work because of this, otherwise you'd have to build your own requests for this.

**Comment by patricknn** [comment]
ahmadnassri, I'm not the website owner I'm just trying to crawl it
The solution is just up there and you ignored.

Your library does not work to scrap any website, it should be, once we can't control the URLs we receive in the redirection.
